<?php

// File ini di-generate otomatis secara berkala melalui php artisan cdn:scan
return [
  'styles' =>   [
    'aos_css' => 'https://unpkg.com/aos@next/dist/aos.css',
    'bootstrap_min_css' => 'https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/css/bootstrap.min.css',
    'all_min_css' => 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css',
    'bootstrap_icons_min_css' => 'https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css',
    'cropper_min_css' => 'https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.5.13/cropper.min.css',
    'style_css' => 'https://cdn.jsdelivr.net/npm/flatpickr/dist/plugins/monthSelect/style.css',
    'flatpickr_min_css' => 'https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css',
    'material_blue_css' => 'https://npmcdn.com/flatpickr/dist/themes/material_blue.css',
    'tom_select_bootstrap5_min_css' => 'https://cdn.jsdelivr.net/npm/tom-select@2.2.2/dist/css/tom-select.bootstrap5.min.css',
    'bootstrap_icons_css' => 'https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css',
    'swiper_bundle_min_css' => 'https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css',
  ],
  'scripts' =>   [
    'chart_js' => 'https://cdn.jsdelivr.net/npm/chart.js',
    'lottie_min_js' => 'https://cdnjs.cloudflare.com/ajax/libs/bodymovin/5.9.6/lottie.min.js',
    'favicon_ico' => 'https://www.google.com/favicon.ico',
    'asset_3fa484' => 'https://cdn.tailwindcss.com',
    'iconify_icon_min_js' => 'https://code.iconify.design/iconify-icon/1.0.7/iconify-icon.min.js',
    'moneymate_id' => 'https://www.instagram.com/moneymate_id',
    '_moneymate_id' => 'https://www.tiktok.com/@moneymate.id',
    'q3imlinyvp' => 'https://stats.uptimerobot.com/Q3ImLiNYVP',
    'aos_js' => 'https://unpkg.com/aos@next/dist/aos.js',
    'holongmarisi_jpeg' => 'https://if.polibatam.ac.id/assets/backupold/img/dosen/holongmarisi.jpeg',
    'lottie_player_js' => 'https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js',
    'credit_removal' => 'https://htmlcodex.com/credit-removal',
    'asset_813a56' => 'https://sroft.my.id',
    'jquery_3_4_1_min_js' => 'https://code.jquery.com/jquery-3.4.1.min.js',
    'bootstrap_bundle_min_js' => 'https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/js/bootstrap.bundle.min.js',
    'lf20_jbrw3hcz_json' => 'https://assets9.lottiefiles.com/packages/lf20_jbrw3hcz.json',
    'qkmdyxsmb5_json' => 'https://lottie.host/0fa01ca4-0702-4bcd-a6e1-c72e85047d67/QkMDyxsMB5.json',
    'kerkvjmu1c_json' => 'https://lottie.host/8fd91a51-0ab6-4abb-a3e4-65f4f3974298/kerKvJmu1C.json',
    'js' => 'https://www.googletagmanager.com/gtag/js?id=G-SEME808CZ1',
    'tom_select_complete_min_js' => 'https://cdn.jsdelivr.net/npm/tom-select@2.2.2/dist/js/tom-select.complete.min.js',
    'flatpickr' => 'https://cdn.jsdelivr.net/npm/flatpickr',
    'id_js' => 'https://cdn.jsdelivr.net/npm/flatpickr/dist/l10n/id.js',
    'index_js' => 'https://cdn.jsdelivr.net/npm/flatpickr@4.6.13/dist/plugins/monthSelect/index.js',
    'asset_377722' => 'https://www.instagram.com/moneymate_id/',
    '_moneymateofficial_id' => 'https://www.youtube.com/@MoneyMateOfficial-id',
    'asset_cf720c' => 'https://www.polibatam.ac.id/',
    'swiper_bundle_min_js' => 'https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js',
    'sweetalert2_11' => 'https://cdn.jsdelivr.net/npm/sweetalert2@11',
    'jquery_3_7_1_min_js' => 'https://code.jquery.com/jquery-3.7.1.min.js',
    'cropper_min_js' => 'https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.5.13/cropper.min.js',
    '4076432_png' => 'https://cdn-icons-png.flaticon.com/512/4076/4076432.png',
    'moneymate_feedback' => 'https://polibatam.id/moneymate-feedback',
  ],
  'fonts' =>   [
    'google_fonts_inter' => 'https://fonts.googleapis.com/css2?family=Roboto+Mono&display=swap',
    'asset_efdfb9' => 'https://fonts.googleapis.com',
    'asset_34cbe6' => 'https://fonts.gstatic.com',
    'google_fonts_inter_heebo' => 'https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600;700&display=swap',
    'google_fonts_inter_poppins' => 'https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap',
    'css' => 'https://fonts.bunny.net/css?family=figtree:400,500,600&display=swap',
  ],
];
